{"uuid": "d44d8a51-9273-41ac-a312-9fcdd019ccf1", "children": ["ee53c66f-ce10-4cc4-bd58-2781f0718570", "18eadcd3-da10-4069-b6f8-6371e9594846", "8e5cfeaf-b21b-482c-94ea-c6102f35fac2"], "befores": [{"name": "xunit_setup_class_fixture_TestAppointment", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=90.0.4430.212)\n\n", "trace": "  File \"d:\\python3.8\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python3.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python3.8\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\PythonTest\\MSH\\script\\test_appointment.py\", line 22, in setup_class\n    self.login_proxy = LoginProxy()\n  File \"D:\\PythonTest\\MSH\\page\\login_page.py\", line 67, in __init__\n    self.login_handle = LoginHandle()\n  File \"D:\\PythonTest\\MSH\\page\\login_page.py\", line 41, in __init__\n    self.login_page = LoginPage()\n  File \"D:\\PythonTest\\MSH\\page\\login_page.py\", line 11, in __init__\n    super().__init__()\n  File \"D:\\PythonTest\\MSH\\base\\base.py\", line 11, in __init__\n    self.driver = UtilsDriver.get_msh_driver()\n  File \"D:\\PythonTest\\MSH\\utils.py\", line 25, in get_msh_driver\n    cls._msh_driver.get('https://apitest.mshchina.com/wechat/#/login?openid=o_YpJwjcmoetXsDKJCBb9AEOvkSM&state=02&language=zh_cn')\n  File \"d:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1669015153286, "stop": 1669015161325}], "start": 1669015153286, "stop": 1669015162143}